name: Test

on:
  push:
    branches: [master]

jobs:
  site:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - run: npm ci
      - run: NODE_ENV=production npm run parcel build examples/simple/index.html --public-url https://aicacia.github.io/ts-cast-canvas-sender/

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
